global:
  name: Azure Data Platform Landscape
  short_name: ADP_Landscape
  repo: valdasm/data-platform-landscape
  website: 'https://landscape.dataplatformschool.com'
  short_domain: https://www.dataplatformschool.com
  company_url: 'https://www.dataplatformschool.com'
  email: valdas@maksimavicius.eu
  self: 'https://www.crunchbase.com/organization/microsoft'
  slack_channel: null
  meta:
    title: Azure Data Platform Landscape
    fb_admin: kam.sadlav
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@VMaksimavicius'
    google_site_verification: xxx
    ms_validate: xxx
  membership: Azure Landscape Members
  flags:
    hide_license_for_categories:
      - Azure Landscape Members
twitter:
  search: landscape.dataplatformschool.com
  url: 'https://landscape.dataplatformschool.com'
  text: Azure Data Platform Landscape
relation:
  label: Azure Cloud Relation
  url: azure
  values:
    - id: hosted
      label: Microsoft Native Services
      children:
        - id: generalavailability
          label: Services in General Availability
          prefix: GA
          tag: GA
          color: '#3570af'
          big_picture_order: 1
          # big_picture_label: GA
          # big_picture_color: 'rgb(24,54,114)'
        - id: preview
          label: Services in Preview
          prefix: Preview
          tag: Preview
          color: '#4470af'
          big_picture_order: 2
          # big_picture_label: Preview
          # big_picture_color: 'rgb(44,14,114)'
        # - id: marketplace
        #   label: Services in Marketplace
        #   prefix: Marketplace
        #   tag: Marketplace
        #   color: '#4470af'
        #   big_picture_order: 3
          # big_picture_label: marketplace
          # big_picture_color: 'rgb(80,80,114)'
    - id: company
      label: Azure Partners
      tag: Company
    - id: member
      label: Open source projects
      tag: open source
    - id: false
      label: Not available on marketplace
      url: 'no'
membership:
  Partner:
    name: MSFT Partner
    label: Partner
    end_user_label: Partner
    funding: Partner
    is_large: true
  Non-partner:
    name: MSFT Non-partner
    label: Non-partner
    end_user_label: Non-partner
    funding: Non-partner
    is_large: true
home:
  header: >
    <h1>Azure Data Platform Landscape</h1> The Azure Data Platform Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Footer
ads:
  - url: 'https://www.linkedin.com/in/valdasm/'
    image: /images/author.jpg
    title: Valdas Maksimavicius
presets:
  - url: /format=card-mode&grouping=category
    label: Cards by categories
  - url: /project=hosted
    label: Azure native services
  - url: /organization=informatica,microsoft
    label: Azure with Informatica 
  - url: /organization=snowflake,microsoft
    label: Azure with Snowflake 
  - url: /organization=databricks,microsoft
    label: Azure with Databricks
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Azure Data Platform Architecture Landscape
    fullscreen_header: See the interactive landscape at l.azuredataplatform.org
    elements:
      - type: VerticalCategory
        category: Data Ingestion
        cols: 3
        width: 200
        height: 380
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Storages
        rows: 3
        width: 450
        height: 180
        top: 0
        left: 225
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Advanced Analytics
        cols: 3
        width: 200
        height: 380
        top: 0
        left: 700
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Business Intelligence
        cols: 3
        width: 200
        height: 380
        top: 0
        left: 920
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Data access
        cols: 3
        width: 200
        height: 380
        top: 0
        left: 1140
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Processing
        rows: 3
        width: 450
        height: 180
        top: 200
        left: 225
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Management
        rows: 2
        width: 1200
        height: 100
        top: 420
        left: 0
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Ops
        rows: 2
        width: 1200
        height: 100
        top: 540
        left: 0
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 1265
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Azure data services, and also shows other possible products within the Azure ecosystem.
            top: 45
            left: 10
            right: 10
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            left: 10
            top: 10
            title: Landscape Logo
  extra:
    tab_index: 1
    url: members
    name: Members
    title: Azure Landscape Companies
    fullscreen_header: Azure Landscape Companies
    fullscreen_hide_grey_logos: true
    elements:
      - type: HorizontalCategory
        category: Partner
        rows: 4
        width: 1250
        height: 200
        top: 0
        left: 0
        color: '#c5c4c2'
        fit_width: true
        offset: 60
      - type: HorizontalCategory
        category: Non-partner
        rows: 4
        width: 1250
        height: 200
        top: 200
        left: 0
        color: '#D4AF37'
        fit_width: true
        offset: 70
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 1265
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Azure data services, and also shows other possible products within the Azure ecosystem.
            top: 45
            left: 10
            right: 10
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            left: 10
            top: 10
            title: Landscape Logo
    category: Azure Landscape Members  

test:
  header: Azure Data Platform Landscape
  section: Cards by categories
  logo: azure-data-factory.svg

