global:
  name: Azure Data Platform Landscape
  short_name: ADP_Landscape
  repo: valdasm/data-platform-landscape
  website: 'https://landscape.xxx.org'
  short_domain: l.xx.org
  company_url: 'https://xx.org'
  email: valdas@maksimavicius.eu
  self: 'https://www.crunchbase.com/organization/microsoft'
  slack_channel: null
  meta:
    title: Azure Data Platform Landscape
    fb_admin: kam.sadlav
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@VMaksimavicius'
    google_site_verification: xxx
    ms_validate: xxx
  membership: Azure Landscape Members
  flags:
    hide_license_for_categories:
      - Azure Landscape Members
twitter:
  search: landscape.xxx.org
  url: 'https://landscape.xxx.org'
  text: Azure Data Platform Landscape
relation:
  label: Azure Cloud Relation
  url: azure
  values:
    - id: hosted
      label: Microsoft Native Services
      children:
        - id: generalavailability
          label: Services in General Availability
          prefix: GA
          tag: GA
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: GA
          big_picture_color: 'rgb(24,54,114)'
        - id: preview
          label: Services in Preview
          prefix: Preview
          tag: Preview
          color: '#4470af'
          big_picture_order: 2
          big_picture_label: Preview
          big_picture_color: 'rgb(44,14,114)'
        - id: marketplace
          label: Services in Marketplace
          prefix: Marketplace
          tag: Marketplace
          color: '#4470af'
          big_picture_order: 3
          big_picture_label: marketplace
          big_picture_color: 'rgb(80,80,114)'
    - id: company
      label: Azure Partners
      tag: Company
    - id: member
      label: Open source projects
      tag: open source
    - id: false
      label: Not available on marketplace
      url: 'no'
membership:
  Platinum:
    name: MSFT Platinum
    label: Platinum Member
    end_user_label: Platinum End User Member
    funding: Platinum
    is_large: true
  Gold:
    name: MSFT Gold
    label: Gold Member
    end_user_label: Gold End User Member
    funding: Gold
    is_large: true
  Other:
    name: MSFT Other
    label: Members
    end_user_label: End User Member
    funding: Smth
    is_large: true
home:
  header: >
    <h1>Azure Data Platform Landscape</h1> The Azure Data Platform Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Footer
ads:
  - url: 'https://www.linkedin.com/in/valdasm/'
    image: /images/author.jpg
    title: Valdas Maksimavicius
  - url: 'https://landing.dataplatformschool.com/azure-data-best-practices'
    image: /images/azure_best_practices.jpg
    title: Azure Best Practices
  - url: 'https://www.valdas.blog'
    image: /images/valdas_blog.jpg
    title: Valdas Blog
presets:
  - url: /format=card-mode&grouping=category
    label: Cards by categories
  - url: /project=hosted
    label: Azure native services
  - url: /organization=informatica,microsoft
    label: Azure with Informatica 
  - url: /organization=snowflake,microsoft
    label: Azure with Snowflake 
  - url: /organization=databricks,microsoft
    label: Azure with Databricks
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Azure Data Platform Architecture Landscape
    fullscreen_header: See the interactive landscape at l.azuredataplatform.org
    elements:
      - type: VerticalCategory
        category: Data Ingestion
        cols: 3
        width: 200
        height: 400
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Storages
        rows: 3
        width: 450
        height: 180
        top: 0
        left: 225
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Advanced Analytics
        cols: 3
        width: 200
        height: 400
        top: 0
        left: 700
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Business Intelligence
        cols: 3
        width: 200
        height: 400
        top: 0
        left: 920
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Data access
        cols: 3
        width: 200
        height: 400
        top: 0
        left: 1140
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Processing
        rows: 3
        width: 450
        height: 180
        top: 180
        left: 225
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Management
        rows: 1
        width: 900
        height: 100
        top: 400
        left: 0
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Ops
        rows: 1
        width: 900
        height: 100
        top: 520
        left: 0
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 1
        width: 900
        height: 100
        top: 640
        left: 0
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 1265
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Azure Data Platform community, and also shows the member organizations of the Azure ecosystem.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.Azure Data Platform.org
            top: 95
            left: 10
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
  extra:
    tab_index: 1
    url: members
    name: Members
    title: Azure Landscape Members
    fullscreen_header: TODO
    fullscreen_hide_grey_logos: true
    elements:
      - type: HorizontalCategory
        category: Platinum
        rows: 4
        width: 1250
        height: 200
        top: 0
        left: 0
        color: '#c5c4c2'
        fit_width: true
        offset: 60
      - type: HorizontalCategory
        category: Gold
        rows: 4
        width: 1250
        height: 200
        top: 200
        left: 0
        color: '#D4AF37'
        fit_width: true
        offset: 70
      - type: LandscapeInfo
        width: 300
        height: 200
        top: 270
        left: 1280
        children:
          - type: text
            text: >
              CNCF has over 500 members including the world’s largest public cloud and enterprise software companies as well over two hundred innovative
              startups. Join your industry peers in helping build and shape the cloud native ecosystem.
            top: 15
            left: 100
            right: 15
            font_size: 11
          - type: image
            image: qr-l.svg
            top: 15
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: m.cncf.io
            top: 105
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            left: 4
            height: 30
            bottom: 13
            width: 116
            title: Landscape Logo
    category: Azure Landscape Members  

test:
  header: Azure Data Platform Landscape
  section: Cards by categories
  logo: azure-data-factory.svg

