global:
  name: Azure Data Platform Landscape
  short_name: ADP_Landscape
  repo: valdasm/data-platform-landscape
  website: 'https://landscape.dataplatformschool.com'
  short_domain: https://www.dataplatformschool.com
  company_url: 'https://www.dataplatformschool.com'
  email: valdas@maksimavicius.eu
  self: 'https://www.crunchbase.com/organization/microsoft'
  slack_channel: null
  meta:
    title: Azure Data Platform Landscape
    fb_admin: kam.sadlav
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@VMaksimavicius'
    google_site_verification: xxx
    ms_validate: xxx
  membership: Azure Landscape Members
  flags:
    hide_license_for_categories:
      - Azure Landscape Members
  hide_funding_and_market_cap: true
twitter:
  search: landscape.dataplatformschool.com
  url: 'https://landscape.dataplatformschool.com'
  text: Azure Data Platform Landscape
relation:
  label: Azure Cloud Relation
  url: azure
  values:
    - id: hosted
      label: Microsoft Native Services
      children:
        - id: generalavailability
          label: Services in General Availability
          prefix: GA
          tag: GA
          color: '#3570af'
          big_picture_order: 1
          # big_picture_label: GA
          # big_picture_color: 'rgb(24,54,114)'
        - id: preview
          label: Services in Preview
          prefix: Preview
          tag: Preview
          color: '#4470af'
          big_picture_order: 2
          big_picture_label: Preview
          big_picture_color: 'rgb(204,90,62)'
        - id: infrastructure
          label: Infrasturcture
          prefix: Infrasturcture
          tag: Infrasturcture
          # big_picture_label: Preview
          # big_picture_color: 'rgb(44,14,114)'
        # - id: marketplace
        #   label: Services in Marketplace
        #   prefix: Marketplace
        #   tag: Marketplace
        #   color: '#4470af'
        #   big_picture_order: 3
          # big_picture_label: marketplace
          # big_picture_color: 'rgb(80,80,114)'
    - id: member
      label: 3rd party components
      tag: 3rd party
    - id: false
      label: Open source
      url: 'no'
    - id: company
      label: Empty
      tag: Company
membership:
  3rdPartyCompanies:
    name: 3rd party components
    label: 3rd party components
    end_user_label: 3rd party components
    funding: 3rd party components
    is_large: true
  # Non-partner:
  #   name: MSFT Non-partner
  #   label: Non-partner
  #   end_user_label: Non-partner
  #   funding: Non-partner
  #   is_large: true
home:
  header: >
    <h1>Azure Data Platform Landscape</h1> The Azure Data Platform landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is a dynamically generated architecture diagram below. 

    The landscape visualizes Azure native services, and also available 3rd party components and services.
    
    The application is based on <a href="http://landscape.cncf.io">CNCF landscape</a> open source code.
  footer: |
    All logos are copyright to their respective owners. Company information details are collected on respective company websites and/or Wikipedia. 
ads:
  - url: 'https://www.linkedin.com/in/valdasm/'
    image: /images/author.png
    title: Valdas Maksimavicius
presets:
  - url: /format=card-mode&grouping=category
    label: Cards by categories
  - url: /organization=microsoft
    label: Azure native services
  - url: /organization=informatica,microsoft
    label: Azure with Informatica 
  - url: /organization=snowflake,microsoft
    label: Azure with Snowflake 
  - url: /organization=databricks,microsoft
    label: Azure with Databricks
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Azure Data Platform Architecture Landscape
    fullscreen_header: See the interactive landscape at https://landscape.dataplatformschool.com/
    elements:
      - type: VerticalCategory
        category: Data Ingestion
        cols: 3
        width: 200
        height: 450
        top: 0
        left: 0
        color: 'rgb(76,54,66)'
        fit_width: true
      - type: HorizontalCategory
        category: Storages
        rows: 3
        width: 550
        height: 170
        top: 0
        left: 225
        color: 'rgb(206,243,196)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Processing
        rows: 3
        width: 550
        height: 270
        top: 180
        left: 225
        color: 'rgb(136,212,202)'
        fit_width: true
      - type: HorizontalCategory
        category: Advanced Analytics
        rows: 3
        width: 550
        height: 170
        top: 0
        left: 800
        color: 'rgb(89,112,156)'
        fit_width: true
      - type: HorizontalCategory
        category: Business Intelligence
        rows: 3
        width: 550
        height: 270
        top: 180
        left: 800
        color: 'rgb(52,71,113)'
        fit_width: true
      - type: VerticalCategory
        category: Data access
        cols: 3
        width: 240
        height: 450
        top: 0
        left: 1380
        color: 'rgb(76,54,66)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Governance
        rows: 2
        width: 1350
        height: 100
        top: 470
        left: 0
        color: 'rgb(206,243,196)'
        fit_width: true
      - type: HorizontalCategory
        category: Data Ops
        rows: 1
        width: 1350
        height: 80
        top: 590
        left: 0
        color: 'rgb(136,212,202)'
        fit_width: true
      - type: LandscapeInfo
        width: 240
        height: 200
        top: 470
        left: 1380
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Azure data services, and also shows other possible products within the Azure ecosystem.
            top: 45
            left: 10
            right: 10
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            left: 10
            top: 10
            title: Landscape Logo
  extra:
    tab_index: 1
    url: members
    name: Members
    title: Azure Landscape Companies
    fullscreen_header: Azure Landscape Companies
    fullscreen_hide_grey_logos: true
    elements:
      - type: HorizontalCategory
        category: 3rdPartyCompanies
        rows: 4
        width: 1250
        height: 350
        top: 0
        left: 0
        color: '#c5c4c2'
        fit_width: true
        offset: 60
     
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 0
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Azure data services, and also shows other possible products within the Azure ecosystem.
            top: 45
            left: 10
            right: 10
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            left: 10
            top: 10
            title: Landscape Logo
    category: Azure Landscape Members  

test:
  header: Azure Data Platform Landscape
  section: Cards by categories
  logo: azure-data-factory.svg

